version: '3.1'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=1
      - POSTGRES_USER=sergey1
      - POSTGRES_DB=work_db
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
    - "5432:5432"
  test-file:
#    build: ./test_server
    restart: always
    image: node
    container_name: backend-tracker
    working_dir: /app
    command: npm run server
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: postgres
    volumes:
#      - ./test_server/node_modules/:/app/node_modules
      - ./backend-tracker/:/app
    depends_on:
    - postgres

volumes:
  pg_selectel:
  backend-tracker:
