version: '3.1'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=1
      - POSTGRES_USER=sergey1
      - POSTGRES_DB=pmt-db
    volumes:
      - ./Docker_Postgre:/var/lib/postgresql/data
    ports:
    - "5432:5432"
  pmt-server:
#    build: ./test_server
    restart: always
    image: node
    container_name: pmt-sever
    working_dir: /app
    command: npm run server
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: postgres
    volumes:
#      - ./test_server/node_modules/:/app/node_modules
      - ./PMT-Server/:/app
    depends_on:
    - postgres

volumes:
    pmt-postgres:
    pmt-server:
  
  
