export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const SETEMAIL = 'SETEMAIL'
export const SETNAME = 'SETNAME'
export const SETPASSWORD = 'SETPASSWORD'

export const SETNAMEOFPROJECT = 'SETNAMEOFPROJECT'
export const SETPROJECT = 'SETPROJECT'
export const SETPROJECTTIME = 'SETPROJECTTIME'
export const DELETEPROJECT = 'DELETEPROJECT'

export const GETUSERS = 'GETUSERS'

export const SETTASKFORTRACKING = 'SETTASKFORTRACKING'

export const SETPROJECTFORTASK = 'SETPROJECTFORTASK'

export const SETNAMETASK = 'SETNAMETASK'
export const SETTIMETASK = 'SETTIMETASK'
export const SETUSERTASK = 'SETUSERTASK'
export const SETTEXTTASK = 'SETTEXTTASK'


export const READTASK = 'READTASK'
export const DELETETASK = 'DELETETASK'

export const SETIDPRO = 'SETIDPRO'

export const SETSTATUS = 'SETSTATUS'
export const SET_PLANNED_TASK = 'SET_PLANNED_TASK'
export const SET_INPROGRESS_TASK = 'SET_INPROGRESS_TASK'
export const SET_DONE_TASK = 'SET_DONE_TASK'

