export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const SETEMAIL = 'SETEMAIL'
export const SETNAME = 'SETNAME'
export const SETPASSWORD = 'SETPASSWORD'
export const SETNAMEOFPROJECT = 'SETNAMEOFPROJECT'
export const SETPROJECT = 'SETPROJECT'
export const GETUSERS = 'GETUSERS'

//export const CREATETASK = 'CREATETASK'

export const SETPROJECTFORTASK = 'SETPROJECTFORTASK'

export const SETNAMETASK = 'SETNAMETASK'
export const SETTIMETASK = 'SETTIMETASK'
export const SETUSERTASK = 'SETUSERTASK'
export const SETTEXTTASK = 'SETTEXTTASK'

export const READTASK = 'READTASK'
export const DELETETASK = 'DELETETASK'